# Generated by Django 4.1.2 on 2022-10-31 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proprietario',
            old_name='CelularWhats',
            new_name='whatsApp',
        ),
    ]
