# Generated by Django 4.1.2 on 2022-11-21 01:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pesquisa',
            name='user_consultor',
        ),
        migrations.AddField(
            model_name='pesquisa',
            name='user_consultor_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='User_Consultor', to='portal.proprietario'),
        ),
    ]
