# Generated by Django 4.1.2 on 2022-11-21 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_alter_pesquisa_user_consultor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imovel',
            name='sem_numero',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Sem número'),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='uso',
            field=models.CharField(blank=True, choices=[('1', 'Residencial'), ('2', 'Comercial'), ('3', 'Misto')], max_length=1, null=True, verbose_name='Uso'),
        ),
    ]
