# Generated by Django 4.1.2 on 2022-10-31 20:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_rename_celularwhats_proprietario_whatsapp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imovel',
            name='corretor',
        ),
        migrations.RemoveField(
            model_name='imovel',
            name='proprietario',
        ),
        migrations.AddField(
            model_name='imovel',
            name='consultor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='portal.proprietario', verbose_name='Consultor'),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='valordevenda',
            field=models.DecimalField(db_column='Valor Pretendido', decimal_places=2, default=0, max_digits=10, verbose_name='Valor de venda'),
        ),
    ]
