# Generated by Django 4.1.2 on 2022-11-22 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_alter_imovel_sem_numero_alter_imovel_uso'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imovel',
            name='suites',
        ),
        migrations.AddField(
            model_name='imovel',
            name='numero_salas',
            field=models.IntegerField(db_column='Nº salas', default=0),
        ),
        migrations.AddField(
            model_name='imovel',
            name='pe_direito_alto',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Pé Direito Alto'),
        ),
    ]
