# Generated by Django 4.1.2 on 2022-11-06 01:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_remove_imovel_corretor_remove_imovel_proprietario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='imovel',
            name='complemento',
            field=models.CharField(blank=True, db_column='Complemento', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='imovel',
            name='logradouro',
            field=models.CharField(blank=True, db_column='Logradouro', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='imovel',
            name='numero',
            field=models.CharField(blank=True, db_column='Número', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='imovel',
            name='sem_numero',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='S/N'),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='consultor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Consultor', to='portal.proprietario'),
        ),
    ]
