# Generated by Django 4.1.2 on 2022-11-06 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_imovel_complemento_imovel_logradouro_imovel_numero_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='imovel',
            name='aquec_solar',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Aquecimento Solar'),
        ),
        migrations.AddField(
            model_name='imovel',
            name='banheiro_empre',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Banheiro empregada'),
        ),
        migrations.AddField(
            model_name='imovel',
            name='churrasqueira',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Churrasqueira'),
        ),
        migrations.AddField(
            model_name='imovel',
            name='estado',
            field=models.CharField(default='SP', max_length=2),
        ),
        migrations.AddField(
            model_name='imovel',
            name='lavabo',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Lavabo'),
        ),
        migrations.AddField(
            model_name='imovel',
            name='numero_banheiros',
            field=models.IntegerField(db_column='Nº total banheiros', default='0'),
        ),
        migrations.AddField(
            model_name='imovel',
            name='numero_dormitorios',
            field=models.IntegerField(db_column='Nº dormitórios', default=0),
        ),
        migrations.AddField(
            model_name='imovel',
            name='pisc_aquec',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Piscina aquecida'),
        ),
        migrations.AddField(
            model_name='imovel',
            name='piscina',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Piscina'),
        ),
        migrations.AddField(
            model_name='imovel',
            name='quarto_empreg',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Quarto empregada'),
        ),
        migrations.AddField(
            model_name='imovel',
            name='suites',
            field=models.IntegerField(db_column='Nº Suítes', default=0),
        ),
        migrations.AddField(
            model_name='imovel',
            name='vestiario',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Vestiário'),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='bairro',
            field=models.CharField(default='----', max_length=100),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='cidade',
            field=models.CharField(default='Ribeirão Preto', max_length=200),
        ),
    ]
