# Generated by Django 4.1.2 on 2022-11-22 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_remove_imovel_suites_imovel_numero_salas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='imovel',
            name='suites',
            field=models.IntegerField(db_column='Nº suítes', default=0),
        ),
    ]
