# Generated by Django 4.1.2 on 2022-11-22 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_imovel_suites'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imovel',
            name='numero_banheiros',
            field=models.IntegerField(db_column='Nº banheiros', default=0),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='numero_salas',
            field=models.IntegerField(blank=True, db_column='Nº salas', default=0, null=True),
        ),
    ]
