# Generated by Django 4.1.2 on 2022-11-23 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0006_alter_imovel_numero_banheiros_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pesquisa',
            name='status',
            field=models.CharField(choices=[('1', 'Oferta'), ('2', 'Vendido')], default=1, max_length=1),
        ),
    ]
