# Generated by Django 4.1.2 on 2022-11-26 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0007_pesquisa_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='pesquisa',
            name='valor_avaliacao',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Valor Avaliação'),
        ),
    ]
