# Generated by Django 4.1.2 on 2022-11-29 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0008_pesquisa_valor_avaliacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='pesquisa',
            name='valor_venda',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor Venda'),
        ),
    ]
